// Decorative components for reusable shapes and paths
export {
  FlowerShape,
  DiamondShape,
  BlobShape,
  CircleShape,
  DotShape,
  RingShape,
  StarShape,
  WaveShape,
  renderShape,
  DecorativeShapes,
  type ShapeConfig,
} from "./DecorativeShapes";

export { AnimatedPath, pathPresets, type PathConfig } from "./AnimatedPath";

// Preset shape configurations
export const shapePresets = {
  // Project hero shapes
  projectHero: [
    {
      type: "flower" as const,
      x: 15,
      y: 50,
      size: 120,
      colors: ["#ec4899", "#f472b6"] as [string, string],
      id: "flower1",
    },
    {
      type: "diamond" as const,
      x: 85,
      y: 15,
      size: 40,
      colors: ["#f97316", "#fbbf24"] as [string, string],
      rotate: 15,
      id: "diamond1",
    },
    {
      type: "blob" as const,
      x: 5,
      y: 75,
      size: 150,
      colors: ["#14b8a6", "#06b6d4"] as [string, string],
      id: "blob1",
    },
    {
      type: "flower" as const,
      x: 60,
      y: 65,
      size: 60,
      colors: ["#f472b6", "#ec4899"] as [string, string],
      id: "flower2",
    },
    {
      type: "circle" as const,
      x: 40,
      y: 20,
      size: 25,
      colors: ["#4ade80", "#22c55e"] as [string, string],
      id: "circle1",
    },
    {
      type: "diamond" as const,
      x: 75,
      y: 70,
      size: 30,
      colors: ["#a855f7", "#c084fc"] as [string, string],
      rotate: 45,
      id: "diamond2",
    },
    {
      type: "flower" as const,
      x: 120,
      y: 40,
      size: 100,
      colors: ["#06b6d4", "#22d3ee"] as [string, string],
      id: "flower3",
    },
    {
      type: "blob" as const,
      x: 150,
      y: 60,
      size: 120,
      colors: ["#f97316", "#fb923c"] as [string, string],
      id: "blob2",
    },
    {
      type: "diamond" as const,
      x: 180,
      y: 25,
      size: 50,
      colors: ["#22c55e", "#4ade80"] as [string, string],
      rotate: 30,
      id: "diamond3",
    },
    {
      type: "flower" as const,
      x: 210,
      y: 55,
      size: 80,
      colors: ["#ec4899", "#f472b6"] as [string, string],
      id: "flower4",
    },
  ],

  // About page shapes
  aboutPage: [
    {
      type: "flower" as const,
      x: 10,
      y: 20,
      size: 80,
      colors: ["#ec4899", "#f472b6"] as [string, string],
      id: "about-flower1",
    },
    {
      type: "diamond" as const,
      x: 90,
      y: 30,
      size: 35,
      colors: ["#f97316", "#fbbf24"] as [string, string],
      rotate: 20,
      id: "about-diamond1",
    },
    {
      type: "circle" as const,
      x: 50,
      y: 70,
      size: 30,
      colors: ["#4ade80", "#22c55e"] as [string, string],
      id: "about-circle1",
    },
    {
      type: "blob" as const,
      x: 5,
      y: 85,
      size: 100,
      colors: ["#14b8a6", "#06b6d4"] as [string, string],
      id: "about-blob1",
    },
    {
      type: "star" as const,
      x: 75,
      y: 15,
      size: 25,
      colors: ["#fbbf24", "#f97316"] as [string, string],
      id: "about-star1",
    },
    {
      type: "ring" as const,
      x: 25,
      y: 55,
      size: 40,
      colors: ["#a855f7", "#c084fc"] as [string, string],
      id: "about-ring1",
    },
    {
      type: "flower" as const,
      x: 120,
      y: 45,
      size: 70,
      colors: ["#06b6d4", "#22d3ee"] as [string, string],
      id: "about-flower2",
    },
    {
      type: "diamond" as const,
      x: 150,
      y: 25,
      size: 45,
      colors: ["#22c55e", "#4ade80"] as [string, string],
      rotate: 35,
      id: "about-diamond2",
    },
    {
      type: "wave" as const,
      x: 180,
      y: 60,
      size: 100,
      colors: ["#ec4899", "#f472b6"] as [string, string],
      id: "about-wave1",
    },
    {
      type: "dot" as const,
      x: 200,
      y: 35,
      size: 20,
      colors: ["#f97316", "#fb923c"] as [string, string],
      id: "about-dot1",
    },
  ],

  // Minimal shapes
  minimal: [
    {
      type: "circle" as const,
      x: 10,
      y: 20,
      size: 30,
      colors: ["#4ade80", "#22c55e"] as [string, string],
      id: "min-circle1",
    },
    {
      type: "diamond" as const,
      x: 85,
      y: 70,
      size: 25,
      colors: ["#f97316", "#fbbf24"] as [string, string],
      rotate: 45,
      id: "min-diamond1",
    },
    {
      type: "dot" as const,
      x: 50,
      y: 50,
      size: 15,
      colors: ["#ec4899", "#f472b6"] as [string, string],
      id: "min-dot1",
    },
  ],

  // Colorful shapes
  colorful: [
    {
      type: "flower" as const,
      x: 5,
      y: 15,
      size: 100,
      colors: ["#ec4899", "#f472b6"] as [string, string],
      id: "color-flower1",
    },
    {
      type: "diamond" as const,
      x: 25,
      y: 60,
      size: 50,
      colors: ["#f97316", "#fbbf24"] as [string, string],
      rotate: 15,
      id: "color-diamond1",
    },
    {
      type: "blob" as const,
      x: 45,
      y: 30,
      size: 120,
      colors: ["#14b8a6", "#06b6d4"] as [string, string],
      id: "color-blob1",
    },
    {
      type: "star" as const,
      x: 70,
      y: 75,
      size: 40,
      colors: ["#fbbf24", "#f97316"] as [string, string],
      id: "color-star1",
    },
    {
      type: "ring" as const,
      x: 90,
      y: 20,
      size: 35,
      colors: ["#a855f7", "#c084fc"] as [string, string],
      id: "color-ring1",
    },
  ],
};
